import React from "react";
import { AbsoluteFill, Audio, Sequence, staticFile } from "remotion";
import { Backdrop } from "./components/Backdrop";
import { AmbientParticles } from "./components/AmbientParticles";
import { SceneWipe } from "./components/SceneWipe";
import { Hook } from "./scenes/Hook";
import { GenericWound } from "./scenes/GenericWound";
import { ThreeLayers } from "./scenes/ThreeLayers";
import { Graph } from "./scenes/Graph";
import { LoopInAction } from "./scenes/LoopInAction";
import { Decision } from "./scenes/Decision";
import { Benchmarks } from "./scenes/Benchmarks";
import { Tagline } from "./scenes/Tagline";
import { Outro } from "./scenes/Outro";
import { COLORS, SCENE } from "./style/tokens";

/**
 * Audio design:
 *   • Ambient music bed (Lyria 2) plays underneath at low volume (~0.22)
 *     so voiceover sits cleanly on top.
 *   • No SFX — deliberately. The music carries the mood; the visuals and
 *     narration carry the meaning.
 *   • Thirteen short voiceover lines, one-to-two per scene. Paced brisk
 *     so the piece never feels unnarrated.
 *
 * All VO generated by Google Cloud TTS Chirp 3 HD (Charon voice) at
 * speaking rate 1.06. See scripts/generate-tts-google.mjs for text.
 */
const VO = [
  // HOOK
  { id: "vo-01-hook-a",    startFrame: 30,   durationFrames: 50 },   // 1.46s
  { id: "vo-01-hook-b",    startFrame: 90,   durationFrames: 75 },   // 2.34s

  // GENERIC WOUND
  { id: "vo-02-wound-a",   startFrame: 195,  durationFrames: 125 },  // 4.01s
  { id: "vo-02-wound-b",   startFrame: 325,  durationFrames: 160 },  // 5.08s

  // THREE LAYERS
  { id: "vo-03-layers-a",  startFrame: 500,  durationFrames: 150 },  // 4.75s
  { id: "vo-03-layers-b",  startFrame: 680,  durationFrames: 120 },  // 3.68s

  // GRAPH
  { id: "vo-04-graph",     startFrame: 855,  durationFrames: 180 },  // 5.75s

  // LOOP IN ACTION
  { id: "vo-05-loop-a",    startFrame: 1065, durationFrames: 65 },   // 2.00s
  { id: "vo-05-loop-b",    startFrame: 1170, durationFrames: 125 },  // 4.01s

  // DECISION
  { id: "vo-06-decision",  startFrame: 1495, durationFrames: 150 },  // 4.81s

  // BENCHMARKS
  { id: "vo-07-bench",     startFrame: 1680, durationFrames: 140 },  // 4.35s

  // TAGLINE
  { id: "vo-08-tagline",   startFrame: 1890, durationFrames: 95 },   // 2.94s

  // OUTRO
  { id: "vo-09-outro",     startFrame: 2080, durationFrames: 120 }   // 3.94s
];

const AMBIENT_BASE = 0.22;

export const Teaser: React.FC = () => {
  return (
    <AbsoluteFill style={{ backgroundColor: COLORS.bg0 }}>
      <Backdrop />
      <AmbientParticles count={42} opacity={0.38} />

      {/* Music bed — sits low so voiceover is unambiguously on top */}
      <Audio src={staticFile("audio/ambient.wav")} volume={AMBIENT_BASE} />

      {/* Voiceover lines */}
      {VO.map((v) => (
        <Sequence
          key={v.id}
          from={v.startFrame}
          durationInFrames={v.durationFrames}
        >
          <Audio src={staticFile(`audio/${v.id}.wav`)} volume={0.95} />
        </Sequence>
      ))}

      {/* ── Scenes + visual-only transitions ──────────────────────── */}
      <Sequence from={SCENE.hook.from} durationInFrames={SCENE.hook.duration}>
        <Hook />
      </Sequence>

      <SceneWipe
        startFrame={SCENE.genericWound.from - 14}
        direction="left-to-right"
        color={COLORS.accent}
        duration={30}
      />
      <Sequence from={SCENE.genericWound.from} durationInFrames={SCENE.genericWound.duration}>
        <GenericWound />
      </Sequence>

      <SceneWipe
        startFrame={SCENE.threeLayers.from - 14}
        direction="right-to-left"
        color={COLORS.observed}
        duration={30}
      />
      <Sequence from={SCENE.threeLayers.from} durationInFrames={SCENE.threeLayers.duration}>
        <ThreeLayers />
      </Sequence>

      <SceneWipe
        startFrame={SCENE.graph.from - 14}
        direction="top-to-bottom"
        color={COLORS.inferred}
        duration={30}
      />
      <Sequence from={SCENE.graph.from} durationInFrames={SCENE.graph.duration}>
        <Graph />
      </Sequence>

      <SceneWipe
        startFrame={SCENE.loopInAction.from - 14}
        direction="left-to-right"
        color={COLORS.inferred}
        duration={30}
      />
      <Sequence from={SCENE.loopInAction.from} durationInFrames={SCENE.loopInAction.duration}>
        <LoopInAction />
      </Sequence>

      <SceneWipe
        startFrame={SCENE.decision.from - 14}
        direction="right-to-left"
        color={COLORS.simulated}
        duration={30}
      />
      <Sequence from={SCENE.decision.from} durationInFrames={SCENE.decision.duration}>
        <Decision />
      </Sequence>

      <SceneWipe
        startFrame={SCENE.benchmarks.from - 14}
        direction="left-to-right"
        color={COLORS.simulated}
        duration={30}
      />
      <Sequence from={SCENE.benchmarks.from} durationInFrames={SCENE.benchmarks.duration}>
        <Benchmarks />
      </Sequence>

      <SceneWipe
        startFrame={SCENE.tagline.from - 14}
        direction="bottom-to-top"
        color={COLORS.accent}
        duration={30}
      />
      <Sequence from={SCENE.tagline.from} durationInFrames={SCENE.tagline.duration}>
        <Tagline />
      </Sequence>

      <SceneWipe
        startFrame={SCENE.outro.from - 14}
        direction="left-to-right"
        color={COLORS.accent}
        duration={30}
        thickness={0.35}
      />
      <Sequence from={SCENE.outro.from} durationInFrames={SCENE.outro.duration}>
        <Outro />
      </Sequence>
    </AbsoluteFill>
  );
};
